// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDHGf7picVng4xpi7n0uxaUfie5AztN3U',
    appId: '1:15767347335:web:0cef688f4eae54042a5822',
    messagingSenderId: '15767347335',
    projectId: 'sustentae-uninter',
    authDomain: 'sustentae-uninter.firebaseapp.com',
    storageBucket: 'sustentae-uninter.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMFPfAubjmAOzT69T9Lm_pWN_wW0KW7Xg',
    appId: '1:15767347335:android:f8f91b756fa0a27e2a5822',
    messagingSenderId: '15767347335',
    projectId: 'sustentae-uninter',
    storageBucket: 'sustentae-uninter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCp0UEAxWP9W7rixQFhwVcsox7enTbftdE',
    appId: '1:15767347335:ios:555665ef209185052a5822',
    messagingSenderId: '15767347335',
    projectId: 'sustentae-uninter',
    storageBucket: 'sustentae-uninter.firebasestorage.app',
    iosBundleId: 'com.example.sustentaeUninter',
  );
}
